cors:
  allowed-origin-patterns:
    - "http://localhost:*"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true